import type { AuditRule, StandardType } from '../types/cad';

export interface StandardDefinition {
  id: StandardType;
  code: string;
  name: string;
  nameZh: string;
  description: string;
  jurisdiction: 'GLOBAL / US (ASME)' | 'INTERNATIONAL (ISO)' | 'AEROSPACE (SAE)' | 'AUTOMOTIVE (AIAG)' | 'ENTERPRISE';
  defaultProjection: 'THIRD_ANGLE' | 'FIRST_ANGLE';
  rules: AuditRule[];
}

export const STANDARDS_DATABASE: Record<StandardType, StandardDefinition> = {
  ASME_Y14_5: {
    id: 'ASME_Y14_5',
    code: 'ASME Y14.5-2018 / Y14.100',
    name: 'ASME Y14.5 Dimensioning & Tolerancing (US / Global Standard)',
    nameZh: 'ASME Y14.5 尺寸与公差标准 (美标/国际通用)',
    description: 'De-facto North American & global standard for technical drawings, GD&T, datum reference frames, and third-angle projection.',
    jurisdiction: 'GLOBAL / US (ASME)',
    defaultProjection: 'THIRD_ANGLE',
    rules: [
      {
        id: 'ASME-TB-01',
        category: 'TITLE_BLOCK',
        title: 'Title Block Mandatory Metadata',
        description: 'Drawing must contain Drawing Number, Part Name, Revision, Material, Finish, and Legal Entity.',
        standardReference: 'ASME Y14.100 Section 4.2',
        severity: 'critical',
      },
      {
        id: 'ASME-TB-02',
        category: 'TITLE_BLOCK',
        title: 'Drawing Approval & Verification Sign-Off',
        description: 'Title block must record Drawn By, Checked By, Approved By, and release date.',
        standardReference: 'ASME Y14.100 Section 4.5',
        severity: 'warning',
      },
      {
        id: 'ASME-PROJ-01',
        category: 'PROJECTION',
        title: 'Third Angle Projection Symbol Defined',
        description: 'ASME drawings require explicit Third Angle Projection symbol (truncated cone) in or adjacent to the title block.',
        standardReference: 'ASME Y14.3 Section 1.4',
        severity: 'critical',
      },
      {
        id: 'ASME-TOL-01',
        category: 'TOLERANCES',
        title: 'General Tolerance Block Callout',
        description: 'A general tolerance note must exist (e.g. UNLESS OTHERWISE SPECIFIED: .X ±0.2, .XX ±0.10, .XXX ±0.025, ANGLES ±0.5°).',
        standardReference: 'ASME Y14.5 Section 2.1.1',
        severity: 'critical',
      },
      {
        id: 'ASME-TOL-02',
        category: 'TOLERANCES',
        title: 'Unit of Measure Specification',
        description: 'Linear unit (MILLIMETERS or INCHES) must be explicitly stated in the general notes or title block.',
        standardReference: 'ASME Y14.5 Section 1.5',
        severity: 'critical',
      },
      {
        id: 'ASME-GDT-01',
        category: 'GD&T',
        title: 'Datum Reference Frame Completeness',
        description: 'Any feature control frame referencing Datum A, B, or C must have corresponding datum feature symbols defined on physical features.',
        standardReference: 'ASME Y14.5 Section 4.4',
        severity: 'critical',
      },
      {
        id: 'ASME-REV-01',
        category: 'REVISION_CONTROL',
        title: 'Revision Block & Change Control',
        description: 'Revision letter must match title block, with revision history entries describing the engineering change.',
        standardReference: 'ASME Y14.35 Section 3',
        severity: 'warning',
      },
      {
        id: 'ASME-DRFT-01',
        category: 'GENERAL_DRAFTING',
        title: 'Diameter & Radius Notation Compliance',
        description: 'Cylindrical features must use "Ø" prefix; circular arcs must use "R" prefix without trailing confusion.',
        standardReference: 'ASME Y14.5 Section 1.7',
        severity: 'warning',
      },
    ],
  },
  ISO_1101: {
    id: 'ISO_1101',
    code: 'ISO 1101 / ISO 2768 / ISO 128',
    name: 'ISO Geometrical Product Specifications (GPS)',
    nameZh: 'ISO 1101 / ISO 2768 国际几何公差标准 (欧标/公制)',
    description: 'International Organization for Standardization specifications for GPS, general tolerance classes (ISO 2768-mK), and first/third angle projection.',
    jurisdiction: 'INTERNATIONAL (ISO)',
    defaultProjection: 'FIRST_ANGLE',
    rules: [
      {
        id: 'ISO-TB-01',
        category: 'TITLE_BLOCK',
        title: 'ISO 7200 Title Block Compliance',
        description: 'Mandatory identification block items: Title, Drawing Number, Sheet Number, Creator, Date, Material specification.',
        standardReference: 'ISO 7200:2004',
        severity: 'critical',
      },
      {
        id: 'ISO-PROJ-01',
        category: 'PROJECTION',
        title: 'Projection Method Identification',
        description: 'Drawing must clearly designate projection standard (First Angle ISO projection cone or Third Angle).',
        standardReference: 'ISO 128-30:2001',
        severity: 'critical',
      },
      {
        id: 'ISO-TOL-01',
        category: 'TOLERANCES',
        title: 'ISO 2768 General Tolerance Class Callout',
        description: 'Drawing must cite a recognized general tolerance class, e.g., "General Tolerances ISO 2768-m" or "ISO 2768-mK".',
        standardReference: 'ISO 2768-1 / 2768-2',
        severity: 'critical',
      },
      {
        id: 'ISO-GDT-01',
        category: 'GD&T',
        title: 'ISO 1101 Geometrical Tolerancing Syntax',
        description: 'Geometrical tolerances must follow ISO 1101 indicator frames and envelope principle designations (E) if required.',
        standardReference: 'ISO 1101:2017',
        severity: 'critical',
      },
      {
        id: 'ISO-SURF-01',
        category: 'GENERAL_DRAFTING',
        title: 'Surface Texture ISO 1302 Specification',
        description: 'General surface texture requirements (e.g. Ra in µm) must be designated in notes or above title block.',
        standardReference: 'ISO 1302:2002',
        severity: 'warning',
      },
      {
        id: 'ISO-REV-01',
        category: 'REVISION_CONTROL',
        title: 'Revision & Status Indication',
        description: 'Release status (e.g., RELEASED, PROTOTYPE, DRAFT) and revision level must be unambiguously stated.',
        standardReference: 'ISO 11442',
        severity: 'warning',
      },
    ],
  },
  AS9102: {
    id: 'AS9102',
    code: 'SAE AS9102 Rev C',
    name: 'Aerospace First Article Inspection (FAI) Standard',
    nameZh: 'AS9102 航空航天首件检验标准 (FAI)',
    description: 'Stringent quality standard for First Article Inspection (FAI Forms 1, 2, and 3), requiring 100% characteristic ballooning and traceability.',
    jurisdiction: 'AEROSPACE (SAE)',
    defaultProjection: 'THIRD_ANGLE',
    rules: [
      {
        id: 'AS9102-01',
        category: 'TITLE_BLOCK',
        title: 'Full Part Traceability Metadata',
        description: 'Requires Part Number, Part Revision, Drawing Number, Drawing Revision, Serial/Lot number, and Raw Material Specification with AMS/ASTM spec.',
        standardReference: 'AS9102 Rev C Form 1/2',
        severity: 'critical',
      },
      {
        id: 'AS9102-02',
        category: 'TOLERANCES',
        title: 'Zero Ambiguity Tolerancing',
        description: 'Every single dimension must have explicit tolerances or traceable general tolerance note; no non-toleranced dimensions allowed.',
        standardReference: 'AS9102 Rev C Form 3',
        severity: 'critical',
      },
      {
        id: 'AS9102-03',
        category: 'GD&T',
        title: 'Key Characteristic (KC) Identification',
        description: 'Safety-critical, flight-critical, or Key Characteristics must be demarcated with special symbol (e.g. ST / KC / <KC>).',
        standardReference: 'AS9103 / AS9102',
        severity: 'warning',
      },
      {
        id: 'AS9102-04',
        category: 'GENERAL_DRAFTING',
        title: 'Drawing Zone Coordinates',
        description: 'Drawing border must contain grid zones (A-F, 1-8) for unambiguous balloon location referencing.',
        standardReference: 'AS9102 Form 3 Field 6',
        severity: 'warning',
      },
    ],
  },
  AIAG_PPAP: {
    id: 'AIAG_PPAP',
    code: 'AIAG PPAP 4th Ed / IATF 16949',
    name: 'Automotive Production Part Approval Process & Control Plan',
    nameZh: 'AIAG 汽车生产件批准程序 (PPAP) 与控制计划',
    description: 'Automotive standard defining Critical to Quality (CTQ) / Special Characteristics, measurement system analysis (MSA), and inspection frequencies.',
    jurisdiction: 'AUTOMOTIVE (AIAG)',
    defaultProjection: 'THIRD_ANGLE',
    rules: [
      {
        id: 'PPAP-01',
        category: 'TITLE_BLOCK',
        title: 'Customer Part Number & Engineering Change Level',
        description: 'Engineering release authorization, customer P/N, drawing revision level, and supplier manufacturing code.',
        standardReference: 'AIAG PPAP Manual 4th Ed',
        severity: 'critical',
      },
      {
        id: 'PPAP-02',
        category: 'GD&T',
        title: 'Special Characteristics Designation',
        description: 'Inverted Delta [∇] or diamond symbol for Safety/Government regulation, or circle for Critical Functional dimensions.',
        standardReference: 'AIAG / IATF 16949',
        severity: 'critical',
      },
      {
        id: 'PPAP-03',
        category: 'TOLERANCES',
        title: 'Process Capability Tolerances (Cpk >= 1.33 / 1.67)',
        description: 'Critical dimensions must specify bilateral symmetrical tolerances suited for SPC and capability studies.',
        standardReference: 'AIAG SPC Manual',
        severity: 'warning',
      },
    ],
  },
  CUSTOM: {
    id: 'CUSTOM',
    code: 'Company Internal Standard',
    name: 'Custom Enterprise Quality & Drafting Standard',
    nameZh: '企业自定义工程制图与质量规范',
    description: 'User-configured rules tailored to company internal drafting handbooks and overseas supplier requirements.',
    jurisdiction: 'ENTERPRISE',
    defaultProjection: 'THIRD_ANGLE',
    rules: [
      {
        id: 'CUST-01',
        category: 'TITLE_BLOCK',
        title: 'China Facility Supplier Code in Title Block',
        description: 'Supplier code or factory location must be documented for China vendor tracking.',
        standardReference: 'Company QA Policy',
        severity: 'warning',
      },
      {
        id: 'CUST-02',
        category: 'TOLERANCES',
        title: 'Bilingual Notes (English & Chinese)',
        description: 'Critical drawing notes should include Chinese translations to prevent fabrication errors on the factory floor.',
        standardReference: 'Global Sourcing Guide',
        severity: 'warning',
      },
    ],
  },
};
