import type { ApqpChecklistItem } from '../types/apqpPpap';

export const DEFAULT_APQP_CHECKLIST: ApqpChecklistItem[] = [
  // ==========================================
  // PHASE 1: PLAN & DEFINE PROGRAM
  // ==========================================
  {
    id: 'CHK-1.1',
    item_no: '1.1',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Voice of the Customer (VOC) Analysis',
    description: 'Customer inputs, warranty data, historical quality reports, and dealer feedback gathered and reviewed.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.1',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-03-15',
    completion_date: '2026-03-14',
    verified_by: 'J. Batten',
    notes: 'Reviewed OEM warranty data and assembly plant VOC scorecards.',
    linked_tab: 'ROADMAP',
  },
  {
    id: 'CHK-1.2',
    item_no: '1.2',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Business Plan & Marketing Strategy',
    description: 'Contract terms, delivery volume schedules, program milestones, and pricing models aligned.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.2',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'S. Vance (Program Mgr)',
    target_date: '2026-03-20',
    completion_date: '2026-03-18',
    verified_by: 'S. Vance',
    notes: 'SOP volume target aligned at 400 pcs/day for Ford F-150 program.',
  },
  {
    id: 'CHK-1.3',
    item_no: '1.3',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Product Benchmark Data & Quality Targets',
    description: 'PPM defect targets, warranty claims limits, and competitor benchmark comparisons documented.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.3',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-03-25',
    completion_date: '2026-03-24',
    verified_by: 'J. Batten',
    notes: 'Target quality level set to <= 15 PPM with Zero Defect gate threshold.',
  },
  {
    id: 'CHK-1.4',
    item_no: '1.4',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Preliminary Bill of Materials (BOM)',
    description: 'Initial component breakdown, raw material alloy grades, and critical sub-supplier parts list.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.7',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'D. Miller (Chief Engineer)',
    target_date: '2026-04-01',
    completion_date: '2026-03-30',
    verified_by: 'D. Miller',
    notes: 'BOM rev 0.9 released in ERP. AISI 8620H steel forgings confirmed.',
  },
  {
    id: 'CHK-1.5',
    item_no: '1.5',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Preliminary Process Flow Diagram',
    description: 'Macro sequence of manufacturing steps from incoming forging receipt to final packaging.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.8',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-04-05',
    completion_date: '2026-04-04',
    verified_by: 'M. Kowalski',
    notes: 'Macro flow approved: Turning -> Hobbing -> Carburizing -> Hard Turning -> Wash -> Pack.',
    linked_tab: 'PROCESS_FLOW',
  },
  {
    id: 'CHK-1.6',
    item_no: '1.6',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Product Assurance Plan & Quality Charter',
    description: 'Program quality reliability objectives, risk mitigation strategies, and engineering sign-offs.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.11',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-04-10',
    completion_date: '2026-04-09',
    verified_by: 'J. Batten',
    notes: 'Quality Charter ratified by executive leadership.',
  },
  {
    id: 'CHK-1.7',
    item_no: '1.7',
    phase: 1,
    section: 'Planning & Definition',
    title: 'Phase 1 Gate Review Sign-Off',
    description: 'Executive and customer sign-off on program definition, resources, and schedule feasibility.',
    aiag_ref: 'AIAG APQP 3rd Ed §1.12',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (VP Quality)',
    target_date: '2026-04-12',
    completion_date: '2026-04-12',
    verified_by: 'J. Batten',
    notes: 'Gate 1 approved with zero open high-severity action items.',
    linked_tab: 'ROADMAP',
  },

  // ==========================================
  // PHASE 2: PRODUCT DESIGN & DEVELOPMENT
  // ==========================================
  {
    id: 'CHK-2.1',
    item_no: '2.1',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Design Failure Mode & Effects Analysis (DFMEA)',
    description: 'Analysis of product design risks, fail-safe geometries, stress concentrations, and safety factors.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.1',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'D. Miller (Chief Engineer)',
    target_date: '2026-05-10',
    completion_date: '2026-05-08',
    verified_by: 'D. Miller',
    notes: 'DFMEA Rev C approved. Gear tooth bending fatigue margin = 2.4.',
  },
  {
    id: 'CHK-2.2',
    item_no: '2.2',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Design for Manufacturability & Assembly (DFM/DFA)',
    description: 'Tooling clearance, clamping rigidity, chip evacuation, and automated robot gripper accessibility evaluated.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.2',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-05-20',
    completion_date: '2026-05-19',
    verified_by: 'M. Kowalski',
    notes: 'DFM feedback incorporated; chamfer added on bore lead-in.',
  },
  {
    id: 'CHK-2.3',
    item_no: '2.3',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Design Verification Plan & Report (DVP&R)',
    description: 'Torsional fatigue, salt spray corrosion, and dynamometer durability test protocol and reports.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.3',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'R. Chen (Testing Lead)',
    target_date: '2026-06-01',
    completion_date: '2026-05-30',
    verified_by: 'R. Chen',
    notes: 'DVP&R passed: 1.5M cycle endurance testing completed with zero cracking.',
  },
  {
    id: 'CHK-2.4',
    item_no: '2.4',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Engineering Drawings & CAD Specs (GD&T Ballooning)',
    description: 'Full 3D CAD definition and 2D blueprint with complete GD&T datum scheme and ballooned dimensions.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.5',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'D. Miller (Chief Engineer)',
    target_date: '2026-06-05',
    completion_date: '2026-06-04',
    verified_by: 'D. Miller',
    notes: 'Ballooned blueprint linked into Quality Compass CAD inspection canvas.',
    linked_tab: 'DIMENSIONAL',
  },
  {
    id: 'CHK-2.5',
    item_no: '2.5',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Material & Heat Treat Specifications',
    description: 'Chemical composition, grain size ASTM >= 5, core hardness, and effective case depth (ECD) defined.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.6',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'K. Patel (Metallurgist)',
    target_date: '2026-06-10',
    completion_date: '2026-06-08',
    verified_by: 'K. Patel',
    notes: 'ECD spec: 0.8mm - 1.2mm @ 50 HRC cutoff. Surface hardness 58-62 HRC.',
  },
  {
    id: 'CHK-2.6',
    item_no: '2.6',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Prototype Build & Prototype Control Plan',
    description: 'First physical prototype sample production under controlled pre-production parameters.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.8',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-06-15',
    completion_date: '2026-06-14',
    verified_by: 'M. Kowalski',
    notes: '50 prototype units machined on toolroom machines and validated.',
    linked_tab: 'CONTROL_PLAN',
  },
  {
    id: 'CHK-2.7',
    item_no: '2.7',
    phase: 2,
    section: 'Product Design & Development',
    title: 'Phase 2 Gate Review & Feasibility Sign-off',
    description: 'Multi-disciplinary team sign-off confirming design feasibility and readiness to build production tooling.',
    aiag_ref: 'AIAG APQP 3rd Ed §2.11',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'D. Miller (Chief Engineer)',
    target_date: '2026-06-20',
    completion_date: '2026-06-20',
    verified_by: 'D. Miller',
    notes: 'Gate 2 approved. Tooling POs released to vendors.',
    linked_tab: 'ROADMAP',
  },

  // ==========================================
  // PHASE 3: PROCESS DESIGN & DEVELOPMENT
  // ==========================================
  {
    id: 'CHK-3.1',
    item_no: '3.1',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Packaging Standards & Specifications',
    description: 'Returnable dunnage, anti-corrosion VCI bags, drop testing, and palletizing load security.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.1',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'L. Gomez (Packaging Eng)',
    target_date: '2026-07-10',
    completion_date: '2026-07-08',
    verified_by: 'L. Gomez',
    notes: 'Returnable ESD/VCI totes approved by Ford material handling.',
  },
  {
    id: 'CHK-3.2',
    item_no: '3.2',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Process Flow Diagram (PFD - Element 5)',
    description: 'Detailed operation-by-operation sequence from receipt through final dock dispatch.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.2 / PPAP Elem 5',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-07-20',
    completion_date: '2026-07-18',
    verified_by: 'M. Kowalski',
    notes: '8-operation process flow diagram configured in Quality Compass PFD module.',
    linked_tab: 'PROCESS_FLOW',
  },
  {
    id: 'CHK-3.3',
    item_no: '3.3',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Floor Plan Layout & Material Logistics Flow',
    description: 'Cellular machining footprint, material buffer staging, and scrap segregation chutes.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.3',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-07-25',
    completion_date: '2026-07-24',
    verified_by: 'M. Kowalski',
    notes: 'Cell layout installed in Bay 4. Forklift traffic lanes isolated.',
  },
  {
    id: 'CHK-3.4',
    item_no: '3.4',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Process FMEA (AIAG-VDA Matrix - Element 6)',
    description: 'Process risk assessment, failure modes, causes, controls, and RPN / Action Priority ranking.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.5 / PPAP Elem 6',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-08-01',
    completion_date: '2026-07-31',
    verified_by: 'J. Batten',
    notes: 'PFMEA matrix established. High RPN items equipped with mist-proof poke-yoke.',
    linked_tab: 'PFMEA',
  },
  {
    id: 'CHK-3.5',
    item_no: '3.5',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Pre-Launch Control Plan (Element 7)',
    description: 'Enhanced inspection frequency, statistical containment, and reaction plans during initial launch.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.6 / PPAP Elem 7',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-08-08',
    completion_date: '2026-08-06',
    verified_by: 'J. Batten',
    notes: 'Pre-launch control plan populated and synchronized with Process Flow operations.',
    linked_tab: 'CONTROL_PLAN',
  },
  {
    id: 'CHK-3.6',
    item_no: '3.6',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Measurement System Analysis (MSA) Plan',
    description: 'List of all variable and attribute gages, calibration certifications, and Gage R&R schedule.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.8 / PPAP Elem 8',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'T. Becker (Gage Metrologist)',
    target_date: '2026-08-12',
    completion_date: '2026-08-10',
    verified_by: 'T. Becker',
    notes: 'MSA plan approved for CMM, Bore Micrometers, and Hardness testers.',
  },
  {
    id: 'CHK-3.7',
    item_no: '3.7',
    phase: 3,
    section: 'Process Design & Development',
    title: 'Phase 3 Gate Review Sign-Off',
    description: 'Operations and Quality leadership approval of production tooling, layout, and process controls.',
    aiag_ref: 'AIAG APQP 3rd Ed §3.10',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Operations Director)',
    target_date: '2026-08-15',
    completion_date: '2026-08-15',
    verified_by: 'M. Kowalski',
    notes: 'Gate 3 approved. Authorized to proceed into Significant Production Run.',
    linked_tab: 'ROADMAP',
  },

  // ==========================================
  // PHASE 4: PRODUCT & PROCESS VALIDATION
  // ==========================================
  {
    id: 'CHK-4.1',
    item_no: '4.1',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Significant Production Run (Run @ Rate - 300 pcs)',
    description: 'Continuous production trial using production tooling, gages, processes, personnel, and cycle time.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.1 / PPAP Elem 14',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-09-02',
    completion_date: '2026-09-02',
    verified_by: 'M. Kowalski',
    notes: '5-Day Run-at-Rate trial completed with 2,277 total parts produced at line speed.',
    linked_tab: 'CAPACITY_ANALYSIS',
  },
  {
    id: 'CHK-4.2',
    item_no: '4.2',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Measurement System Analysis (Gage R&R < 10%)',
    description: 'Variable Gage R&R studies on critical features using 10 parts, 3 operators, 3 trials.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.2 / PPAP Elem 8',
    is_gate_prerequisite: false,
    status: 'COMPLETED',
    assigned_to: 'T. Becker (Metrologist)',
    target_date: '2026-09-03',
    completion_date: '2026-09-03',
    verified_by: 'T. Becker',
    notes: 'Zeiss CMM Gage R&R = 6.4% GRR (Well within < 10% acceptable AIAG limit).',
  },
  {
    id: 'CHK-4.3',
    item_no: '4.3',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Initial Process Capability Studies (Cpk >= 1.67)',
    description: 'Statistical capability study on all special characteristics (Critical / Diamond features).',
    aiag_ref: 'AIAG APQP 3rd Ed §4.3 / PPAP Elem 11',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-09-04',
    completion_date: '2026-09-04',
    verified_by: 'J. Batten',
    notes: 'Pinion bore Cpk = 1.84, Pitch runout Cpk = 1.72 (Both exceed 1.67 requirement).',
  },
  {
    id: 'CHK-4.4',
    item_no: '4.4',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Full Dimensional Layout Inspection (Form CFG-1003)',
    description: '100% layout inspection of 5 sample parts against all ballooned print dimensions and GD&T callouts.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.5 / PPAP Elem 9',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'T. Becker (Metrologist)',
    target_date: '2026-09-05',
    completion_date: '2026-09-05',
    verified_by: 'T. Becker',
    notes: 'All 5 sample parts evaluated across all features. 100% PASS on Form CFG-1003.',
    linked_tab: 'DIMENSIONAL',
  },
  {
    id: 'CHK-4.5',
    item_no: '4.5',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Capacity Analysis & Run @ Rate Evaluation',
    description: 'Validation that production line demonstrates required daily demand within <= 85% rated capacity.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.6 / PPAP Elem 14',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-09-06',
    completion_date: '2026-09-06',
    verified_by: 'M. Kowalski',
    notes: 'Rated capacity: 512 pcs/day vs Demand 400 pcs/day. Loading = 78.1% (Verdict: GOOD).',
    linked_tab: 'CAPACITY_ANALYSIS',
  },
  {
    id: 'CHK-4.6',
    item_no: '4.6',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Production Control Plan Sign-Off',
    description: 'Transition from Pre-Launch Control Plan to long-term Production Control Plan signed by all parties.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.7 / PPAP Elem 7',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-09-06',
    completion_date: '2026-09-06',
    verified_by: 'J. Batten',
    notes: 'Production control plan finalized with customer-approved sampling frequencies.',
    linked_tab: 'CONTROL_PLAN',
  },
  {
    id: 'CHK-4.7',
    item_no: '4.7',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'PPAP 18-Element Dossier Verification',
    description: 'Audit and package all 18 standard AIAG PPAP 4th Edition elements for submission package.',
    aiag_ref: 'AIAG PPAP 4th Edition Level 3',
    is_gate_prerequisite: true,
    status: 'COMPLETED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-09-07',
    completion_date: '2026-09-07',
    verified_by: 'J. Batten',
    notes: '17 of 18 elements included (AAR marked N/A for mechanical transmission component). 100% ready.',
    linked_tab: 'ELEMENTS_18',
  },
  {
    id: 'CHK-4.8',
    item_no: '4.8',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Part Submission Warrant (PSW Form CFG-1001)',
    description: 'Formal warrant signed by authorized organization representative and submitted to customer STA.',
    aiag_ref: 'AIAG PPAP Elem 18 (CFG-1001)',
    is_gate_prerequisite: true,
    status: 'IN_PROGRESS',
    assigned_to: 'J. Batten (VP Quality)',
    target_date: '2026-09-10',
    completion_date: null,
    verified_by: null,
    notes: 'Warrant signed internally by Quality Director. Awaiting final Ford STA disposition.',
    linked_tab: 'PSW_WARRANT',
  },
  {
    id: 'CHK-4.9',
    item_no: '4.9',
    phase: 4,
    section: 'Product & Process Validation',
    title: 'Phase 4 Gate Review Sign-Off',
    description: 'Customer OEM STA / Engineering sign-off on full PPAP submission and authorization for series production.',
    aiag_ref: 'AIAG APQP 3rd Ed §4.9',
    is_gate_prerequisite: true,
    status: 'IN_PROGRESS',
    assigned_to: 'Pending Customer STA Review',
    target_date: '2026-09-15',
    completion_date: null,
    verified_by: null,
    notes: 'Scheduled for Ford Supplier Technical Assistance (STA) formal launch review.',
    linked_tab: 'ROADMAP',
  },

  // ==========================================
  // PHASE 5: FEEDBACK, ASSESSMENT & CORRECTIVE ACTION
  // ==========================================
  {
    id: 'CHK-5.1',
    item_no: '5.1',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Early Production Containment & Safe Launch Plan',
    description: '100% secondary inspection containment gate active during first 90 days of series production.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.1',
    is_gate_prerequisite: false,
    status: 'NOT_STARTED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-10-01',
    completion_date: null,
    verified_by: null,
    notes: 'Safe launch inspection station engineered for Bay 4 exit.',
  },
  {
    id: 'CHK-5.2',
    item_no: '5.2',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Statistical Process Control (SPC) Monitoring & Yield',
    description: 'X-bar and R charts active on all CNC machines with automated alert triggers for out-of-control runs.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.2',
    is_gate_prerequisite: false,
    status: 'NOT_STARTED',
    assigned_to: 'J. Batten (Lead Quality Eng)',
    target_date: '2026-10-15',
    completion_date: null,
    verified_by: null,
    notes: 'Digital telemetry interface mapped to machine controllers.',
  },
  {
    id: 'CHK-5.3',
    item_no: '5.3',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Ramp-Up Delivery & On-Time Performance Metrics',
    description: 'Track OTD, line stoppage rates, and expedited freight counts against contracted SLA.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.3',
    is_gate_prerequisite: false,
    status: 'NOT_STARTED',
    assigned_to: 'S. Vance (Program Mgr)',
    target_date: '2026-11-01',
    completion_date: null,
    verified_by: null,
    notes: 'Logistics tracking integrated with Odoo ERP dispatch.',
  },
  {
    id: 'CHK-5.4',
    item_no: '5.4',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Customer Satisfaction & Warranty Tracking',
    description: 'Zero customer disruption tracking, initial quality study (IQS) feedback, and warranty claims dashboard.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.4',
    is_gate_prerequisite: false,
    status: 'NOT_STARTED',
    assigned_to: 'J. Batten (VP Quality)',
    target_date: '2026-11-15',
    completion_date: null,
    verified_by: null,
    notes: 'Customer scorecard monitored monthly.',
  },
  {
    id: 'CHK-5.5',
    item_no: '5.5',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Continuous Improvement (Kaizen) & Lessons Learned',
    description: 'Archive engineering changes, cycle time reductions, and tooling wear insights into institutional repository.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.5',
    is_gate_prerequisite: false,
    status: 'NOT_STARTED',
    assigned_to: 'M. Kowalski (Mfg Eng)',
    target_date: '2026-12-01',
    completion_date: null,
    verified_by: null,
    notes: 'Knowledge base repository provisioned in Quality Compass.',
  },
  {
    id: 'CHK-5.6',
    item_no: '5.6',
    phase: 5,
    section: 'Feedback & Corrective Action',
    title: 'Program Closeout & Gate 5 Final Sign-off',
    description: 'Official transition of launch program to steady-state plant manufacturing operations.',
    aiag_ref: 'AIAG APQP 3rd Ed §5.6',
    is_gate_prerequisite: true,
    status: 'NOT_STARTED',
    assigned_to: 'J. Batten (VP Quality)',
    target_date: '2026-12-15',
    completion_date: null,
    verified_by: null,
    notes: 'Final gate closure upon 90 days zero-defect series production.',
    linked_tab: 'ROADMAP',
  },
];
